version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - converter_app
      - converter_db
  converter_app:
    container_name: converter_app
    build: ./converter_app
    environment:
      DB_NAME: converter
      DB_USER: postgres
      DB_HOST: converter_db
      DB_PORT: 5432
      DB_PASSWORD: postgres
      JWT_ALGORITHM: HS256
      JWT_SECRET_KEY: secret
      JWT_TYPE: Bearer
      JWT_NAME: Authorization
      CELERY_QUEUE: convertions
    depends_on:
      - converter_db
      - redis
  converter_db:
    container_name: converter_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: converter
    volumes:
      - converter_db:/var/lib/postgresql/data/
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
  celery:
    container_name: celery
    build: ./tasks
    depends_on:
      - converter_db
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  converter_db:


